name: Post RSS to Bluesky

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install atproto fastfeedparser beautifulsoup4 httpx arrow
      - name: Run script
        run: |
          python3 rss2bsky.py https://www.rac1.cat/rss/home.xml \
            "${{ secrets.BLSKY_HANDLE }}" \
            "${{ secrets.BLSKY_USERNAME }}" \
            "${{ secrets.BLSKY_APP_PASSWORD }}"